// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/nothome": {
    params: {};
  };
  "/app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/nothome" | "/app";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/nothome.tsx": {
    id: "routes/nothome";
    page: "/nothome";
  };
  "routes/App.tsx": {
    id: "routes/App";
    page: "/app";
  };
};