// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/help/privacy-policy": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/help" | "/help/privacy-policy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/Landing.tsx": {
    id: "routes/Landing";
    page: "/";
  };
  "routes/help.tsx": {
    id: "routes/help";
    page: "/help" | "/help/privacy-policy";
  };
  "routes/help-home.tsx": {
    id: "routes/help-home";
    page: "/help";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/help/privacy-policy";
  };
};